/**
 * Categoria de item por capítulo do NCM (2 primeiros dígitos), conforme
 * Sistema Harmonizado (SH). Usado para classificar automaticamente os itens
 * das NF-e recebidas (compras) sem precisar de cadastro manual por produto.
 */

const CAPITULOS_NCM = {
  "01": "Animais vivos",
  "02": "Carnes e miudezas comestíveis",
  "03": "Peixes e crustáceos",
  "04": "Leite, laticínios, ovos e mel",
  "05": "Outros produtos de origem animal",
  "06": "Plantas vivas e produtos de floricultura",
  "07": "Produtos hortícolas",
  "08": "Frutas",
  "09": "Café, chá, mate e especiarias",
  "10": "Cereais",
  "11": "Produtos da indústria de moagem",
  "12": "Sementes e grãos oleaginosos",
  "13": "Gomas, resinas e extratos vegetais",
  "14": "Matérias para entrançar",
  "15": "Gorduras e óleos animais/vegetais",
  "16": "Preparações de carne e peixe",
  "17": "Açúcares e produtos de confeitaria",
  "18": "Cacau e suas preparações",
  "19": "Preparações à base de cereais/farinha",
  "20": "Preparações de produtos hortícolas/frutas",
  "21": "Preparações alimentícias diversas",
  "22": "Bebidas, líquidos alcoólicos e vinagres",
  "23": "Resíduos e desperdícios alimentares",
  "24": "Fumo e sucedâneos",
  "25": "Sal, gesso, cal, cimento e pedras",
  "26": "Minérios, escórias e cinzas",
  "27": "Combustíveis minerais e óleos",
  "28": "Produtos químicos inorgânicos",
  "29": "Produtos químicos orgânicos",
  "30": "Produtos farmacêuticos",
  "31": "Adubos e fertilizantes",
  "32": "Tintas, vernizes e corantes",
  "33": "Óleos essenciais e cosméticos",
  "34": "Sabões, ceras e velas",
  "35": "Matérias albuminoides e colas",
  "36": "Pólvoras e explosivos",
  "37": "Produtos para fotografia/cinema",
  "38": "Produtos químicos diversos",
  "39": "Plásticos e suas obras",
  "40": "Borracha e suas obras",
  "41": "Peles e couros",
  "42": "Obras de couro, malas e artefatos",
  "43": "Peles com pelo e suas obras",
  "44": "Madeira e suas obras",
  "45": "Cortiça e suas obras",
  "46": "Obras de matérias para entrançar",
  "47": "Pastas de madeira/celulose",
  "48": "Papel e cartão",
  "49": "Livros, jornais e impressos",
  "50": "Seda",
  "51": "Lã e pelos finos",
  "52": "Algodão",
  "53": "Outras fibras têxteis vegetais",
  "54": "Filamentos sintéticos/artificiais",
  "55": "Fibras sintéticas/artificiais descontínuas",
  "56": "Pastas, feltros e falsos tecidos",
  "57": "Tapetes e revestimentos têxteis",
  "58": "Tecidos especiais e bordados",
  "59": "Tecidos impregnados e revestidos",
  "60": "Tecidos de malha",
  "61": "Vestuário de malha",
  "62": "Vestuário exceto malha",
  "63": "Outros artefatos têxteis confeccionados",
  "64": "Calçados e polainas",
  "65": "Chapéus e artefatos de uso semelhante",
  "66": "Guarda-chuvas e bengalas",
  "67": "Penas, flores artificiais e perucas",
  "68": "Obras de pedra, gesso e cimento",
  "69": "Produtos cerâmicos",
  "70": "Vidro e suas obras",
  "71": "Pérolas, pedras e metais preciosos, joalheria",
  "72": "Ferro e aço",
  "73": "Obras de ferro fundido, ferro ou aço",
  "74": "Cobre e suas obras",
  "75": "Níquel e suas obras",
  "76": "Alumínio e suas obras",
  "78": "Chumbo e suas obras",
  "79": "Zinco e suas obras",
  "80": "Estanho e suas obras",
  "81": "Outros metais comuns",
  "82": "Ferramentas e talheres de metal comum",
  "83": "Outras obras de metais comuns",
  "84": "Máquinas, reatores e equipamentos mecânicos",
  "85": "Máquinas e equipamentos elétricos",
  "86": "Material ferroviário",
  "87": "Veículos automóveis e suas partes",
  "88": "Aeronaves e suas partes",
  "89": "Embarcações",
  "90": "Instrumentos de óptica, medição e EPI",
  "91": "Relógios",
  "92": "Instrumentos musicais",
  "93": "Armas e munições",
  "94": "Móveis e mobiliário",
  "95": "Brinquedos e artigos esportivos",
  "96": "Obras diversas (canetas, escovas, etc.)",
  "97": "Objetos de arte e antiguidades",
};

function categoriaPorNcm(ncm) {
  if (!ncm) return "Sem NCM";
  const capitulo = String(ncm).replace(/\D/g, "").slice(0, 2);
  return CAPITULOS_NCM[capitulo] || `Capítulo NCM ${capitulo || "?"}`;
}

module.exports = { CAPITULOS_NCM, categoriaPorNcm };
